import "../../globals.css"
import type { Metadata } from "next"
import { ReactNode } from "react"
import { NextIntlClientProvider } from "next-intl"
import { setRequestLocale } from "next-intl/server"
import { getMessages } from "next-intl/server"

import {routing} from "../../i18n/routing"

import { Nav } from "@/ui/components/Nav"

type LayoutTypes = {
  children: ReactNode
  params: Promise<{ locale: string }>
}


export const metadata: Metadata = {
  title: "Felipe Maifredo Portfolio",
  description: "Generated by create next app",
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}))
}

export default async function LocaleLayout({ children, params }: LayoutTypes) {
  setRequestLocale((await params).locale)
  const messages = await getMessages()

  return (
    <NextIntlClientProvider messages={messages}>
      <html>
        <body data-theme="t-light" data-color="t-green">
          <Nav />
          {children}
        </body>
      </html>
    </NextIntlClientProvider>
  )
}
