import "../../globals.css"
import type { Metadata } from "next"
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import {routing} from '../../i18n/routing'
import {unstable_setRequestLocale} from 'next-intl/server'

type LayoutTypes = {
  children: React.ReactNode
  params: { locale: string }
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}));
}

export default async function LocaleLayout({ children, params: { locale } }: LayoutTypes) {
  const messages = await getMessages()
  unstable_setRequestLocale(locale)

  return (
    <NextIntlClientProvider messages={messages}>
      <html lang={locale}>
        <body>
          {children}
        </body>
      </html>
    </NextIntlClientProvider>
  )
}
